# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import league.models
import league.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True, verbose_name='date')),
                ('robot1_score', models.FloatField()),
                ('robot2_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('registration_date_start', models.DateField(verbose_name='registration starting date')),
                ('registration_date_end', models.DateField(verbose_name='registration ending date')),
                ('date_start', models.DateField(verbose_name='starting date')),
                ('date_end', models.DateField(verbose_name='ending date')),
                ('num_robots', models.PositiveSmallIntegerField(verbose_name='number of robots')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FileField(storage=league.storages.OverwriteStorage(), upload_to=league.models.user_directory_path)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League'),
        ),
        migrations.AddField(
            model_name='game',
            name='robot1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot1', to='league.Robot'),
        ),
        migrations.AddField(
            model_name='game',
            name='robot2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot2', to='league.Robot'),
        ),
    ]
