# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import league.models
import league.storages


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='num_teams',
            field=models.PositiveSmallIntegerField(verbose_name='number of teams'),
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.FileField(storage=league.storages.OverwriteStorage(), upload_to=league.models.user_directory_path),
        ),
    ]
