# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'A league with that name already exists.'}, help_text='Required. 150 characters or fewer.', max_length=150, unique=True, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('registration_date_start', models.DateField(verbose_name='registration starting date')),
                ('registration_date_end', models.DateField(verbose_name='registration ending date')),
                ('date_start', models.DateField(verbose_name='starting date')),
                ('date_end', models.DateField(verbose_name='ending date')),
                ('num_robots', models.PositiveSmallIntegerField(verbose_name='number of robots')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='games.Game')),
                ('robots', models.ManyToManyField(blank=True, related_name='leagues', to='robots.Robot')),
            ],
        ),
    ]
